const EVENTS = Object.freeze({
  USER_READY_FOR_VERIFICATION: "USER_READY_FOR_VERIFICATION",
  VERIFICATION_PREPARING: "VERIFICATION_PREPARING",
  VERIFICATION_AVAILABLE: "VERIFICATION_AVAILABLE",
  VERIFICATION_SYSTEM_ERROR: "VERIFICATION_SYSTEM_ERROR",
  VERIFICATION_RETRY_AVAILABLE: "VERIFICATION_RETRY_AVAILABLE",
  VERIFICATION_COMPLETED: "VERIFICATION_COMPLETED",
});

module.exports = { EVENTS };